CREATE TABLE public.sheets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT auth.uid(), name text NOT NULL DEFAULT 'Novo Herdeiro', lineage text NOT NULL DEFAULT 'Humano', stage text NOT NULL DEFAULT '', concept text NOT NULL DEFAULT '', weapon text NOT NULL DEFAULT '', corpo int NOT NULL DEFAULT 1 CHECK (corpo BETWEEN 1 AND 5), mente int NOT NULL DEFAULT 1 CHECK (mente BETWEEN 1 AND 5), espirito int NOT NULL DEFAULT 1 CHECK (espirito BETWEEN 1 AND 5), pv_current int NOT NULL DEFAULT 25, pv_max int NOT NULL DEFAULT 25, pf_current int NOT NULL DEFAULT 0, pf_max int NOT NULL DEFAULT 20, karma int NOT NULL DEFAULT 0, gs int NOT NULL DEFAULT 1, exhaustion int NOT NULL DEFAULT 0, sync jsonb NOT NULL DEFAULT '[]'::jsonb, nomenclatures jsonb NOT NULL DEFAULT '[]'::jsonb, inventory jsonb NOT NULL DEFAULT '[]'::jsonb, story text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sheets TO authenticated;
GRANT ALL ON public.sheets TO service_role;
ALTER TABLE public.sheets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner reads sheets" ON public.sheets FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Owner creates sheets" ON public.sheets FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "Owner edits sheets" ON public.sheets FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Owner deletes sheets" ON public.sheets FOR DELETE TO authenticated USING (user_id = auth.uid());
CREATE TABLE public.campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), master_id uuid NOT NULL DEFAULT auth.uid(), name text NOT NULL DEFAULT 'Nova mesa', code text NOT NULL UNIQUE DEFAULT upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)), scene text NOT NULL DEFAULT '', round int NOT NULL DEFAULT 1, turn_index int NOT NULL DEFAULT 0, combat_active boolean NOT NULL DEFAULT false, log jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.campaigns TO authenticated;
GRANT ALL ON public.campaigns TO service_role;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Master reads campaigns" ON public.campaigns FOR SELECT TO authenticated USING (master_id = auth.uid());
CREATE POLICY "Master creates campaigns" ON public.campaigns FOR INSERT TO authenticated WITH CHECK (master_id = auth.uid());
CREATE POLICY "Master edits campaigns" ON public.campaigns FOR UPDATE TO authenticated USING (master_id = auth.uid()) WITH CHECK (master_id = auth.uid());
CREATE POLICY "Master deletes campaigns" ON public.campaigns FOR DELETE TO authenticated USING (master_id = auth.uid());
CREATE TABLE public.npcs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE, name text NOT NULL DEFAULT 'Novo inimigo', kind text NOT NULL DEFAULT 'inimigo' CHECK (kind IN ('npc','inimigo')), hidden boolean NOT NULL DEFAULT true, pv_current int NOT NULL DEFAULT 25, pv_max int NOT NULL DEFAULT 25, pf_current int NOT NULL DEFAULT 0, pf_max int NOT NULL DEFAULT 20, corpo int NOT NULL DEFAULT 1, mente int NOT NULL DEFAULT 1, espirito int NOT NULL DEFAULT 1, esquiva int NOT NULL DEFAULT 10, bloqueio int NOT NULL DEFAULT 3, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.npcs TO authenticated;
GRANT ALL ON public.npcs TO service_role;
ALTER TABLE public.npcs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Master reads npcs" ON public.npcs FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Master creates npcs" ON public.npcs FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Master edits npcs" ON public.npcs FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Master deletes npcs" ON public.npcs FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));