CREATE TABLE public.profiles (id uuid PRIMARY KEY DEFAULT auth.uid(), display_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "Update own profile" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.campaign_members (campaign_id uuid NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE, user_id uuid NOT NULL DEFAULT auth.uid(), character_id uuid REFERENCES public.sheets(id) ON DELETE SET NULL, joined_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(campaign_id,user_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.campaign_members TO authenticated;
GRANT ALL ON public.campaign_members TO service_role;
ALTER TABLE public.campaign_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Member reads membership" ON public.campaign_members FOR SELECT TO authenticated USING (user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Member updates own character" ON public.campaign_members FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid() AND (character_id IS NULL OR EXISTS (SELECT 1 FROM public.sheets s WHERE s.id = character_id AND s.user_id = auth.uid())));
CREATE POLICY "Member leaves" ON public.campaign_members FOR DELETE TO authenticated USING (user_id = auth.uid());
CREATE TABLE public.campaign_secrets (campaign_id uuid PRIMARY KEY REFERENCES public.campaigns(id) ON DELETE CASCADE, password_hash text NOT NULL);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.campaign_secrets TO authenticated;
GRANT ALL ON public.campaign_secrets TO service_role;
ALTER TABLE public.campaign_secrets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Master reads secret" ON public.campaign_secrets FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Master updates secret" ON public.campaign_secrets FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE POLICY "Master deletes secret" ON public.campaign_secrets FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.campaigns c WHERE c.id = campaign_id AND c.master_id = auth.uid()));
CREATE OR REPLACE FUNCTION public.set_campaign_password(p_campaign uuid,p_password text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN IF auth.uid() IS NULL OR NOT EXISTS (SELECT 1 FROM public.campaigns WHERE id=p_campaign AND master_id=auth.uid()) THEN RAISE EXCEPTION 'Acesso negado'; END IF; IF length(p_password) < 4 OR length(p_password) > 100 THEN RAISE EXCEPTION 'A senha deve ter entre 4 e 100 caracteres'; END IF; INSERT INTO public.campaign_secrets(campaign_id,password_hash) VALUES (p_campaign, crypt(p_password,gen_salt('bf'))) ON CONFLICT (campaign_id) DO UPDATE SET password_hash=EXCLUDED.password_hash; END; $$;
REVOKE ALL ON FUNCTION public.set_campaign_password(uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_campaign_password(uuid,text) TO authenticated;
CREATE OR REPLACE FUNCTION public.join_campaign(p_code text,p_password text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE room_id uuid; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Entre na sua conta para participar'; END IF; SELECT c.id INTO room_id FROM public.campaigns c JOIN public.campaign_secrets s ON s.campaign_id=c.id WHERE c.code=upper(trim(p_code)) AND s.password_hash=crypt(p_password,s.password_hash) LIMIT 1; IF room_id IS NULL THEN RAISE EXCEPTION 'Código ou senha incorretos'; END IF; INSERT INTO public.campaign_members(campaign_id,user_id) VALUES(room_id,auth.uid()) ON CONFLICT DO NOTHING; RETURN room_id; END; $$;
REVOKE ALL ON FUNCTION public.join_campaign(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.join_campaign(text,text) TO authenticated;
CREATE POLICY "Members read campaigns" ON public.campaigns FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.campaign_members m WHERE m.campaign_id = id AND m.user_id = auth.uid()));
CREATE POLICY "Members read visible npcs" ON public.npcs FOR SELECT TO authenticated USING (hidden = false AND EXISTS (SELECT 1 FROM public.campaign_members m WHERE m.campaign_id = campaign_id AND m.user_id = auth.uid()));
CREATE POLICY "Members read party sheets" ON public.sheets FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.campaign_members mine JOIN public.campaign_members theirs ON theirs.campaign_id=mine.campaign_id WHERE mine.user_id=auth.uid() AND theirs.user_id=public.sheets.user_id));
ALTER PUBLICATION supabase_realtime ADD TABLE public.campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE public.npcs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.campaign_members;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sheets;